# Generated by Django 2.1.7 on 2019-03-05 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=25)),
                ('pcost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pcolor', models.CharField(default='black', max_length=25)),
                ('pmfd', models.DateTimeField(default=datetime.datetime(2019, 3, 5, 6, 0, 17, 904243))),
                ('pexfd', models.DateTimeField(default=datetime.datetime(2021, 3, 4, 6, 0, 17, 904257))),
            ],
        ),
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('user', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=20, unique=True)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
    ]
